spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 5640000010
  secret: user_token_native_application_changed_#2
gateway:
  ip: 172.18.0.6
